name: utility
description: utility
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  chopper: ^8.4.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.22.0
  very_good_analysis: ^10.0.0
