name: post_api_service
description: post http api
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  chopper: ^8.4.0
  freezed_annotation: ^3.0.0
  json_serializable_chopper_converter: ^1.0.0

dev_dependencies:
  build_runner: ^2.10.3
  chopper_generator: ^8.4.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.22.0
  very_good_analysis: ^10.0.0
