name: post_api_service
description: post http api
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  chopper: ^8.4.0
  blog_domain: ^0.1.0

dev_dependencies:
  build_runner: ^2.6.0
  chopper_generator: ^8.4.0
  mocktail: ^1.0.4
  test: ^1.22.0
  very_good_analysis: ^10.0.0
