name: post_http_repository
description: post http repository
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  blog_domain: ^0.1.0
  post_api_service: ^0.1.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.22.0
  very_good_analysis: ^10.0.0
