name: posts
description: posts feature
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.1.0
  blog_domain: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
